### PR TITLE
feat: Backend Comment merge branch develop

### PR DESCRIPTION
**Pull request by deveyy**

### CODE REVIEW

**Review by ddthien-coder — COMMENTED** [review]
fix conflict

**Comment by deveyy** [comment]
> fix conflict

fixed

https://github.com/deveyy/bdigital-backend/pull/18/commits/06e0eff44aef50565ab2e3dabb6b3970f4843b09

**Comment by ddthien-coder** [comment]
> > fix conflict
> 
> fixed
> 
> [06e0eff](https://github.com/deveyy/bdigital-backend/commit/06e0eff44aef50565ab2e3dabb6b3970f4843b09)

approve

**Comment by ddthien-coder** [comment]
> > > fix conflict
> > 
> > 
> > fixed
> > [06e0eff](https://github.com/deveyy/bdigital-backend/commit/06e0eff44aef50565ab2e3dabb6b3970f4843b09)
> 
> approve

Check file

**Review by ddthien-coder — APPROVED** [review]
Approve

feat: Backend Comment merge branch develop

done fixed conflict: https://github.com/deveyy/bdigital-backend/pull/18/commits/06e0eff44aef50565ab2e3dabb6b3970f4843b09

**Pull request merged**
