### PR TITLE
add login with jwt session

### PR DESCRIPTION
**Pull request by deveyy**

### CODE REVIEW

**Review by ddthien-coder — COMMENTED** [review]
fix conflict

**Comment by deveyy** [comment]
> fix conflict

fixed @a4d17c7

**Comment by deveyy** [comment]
> 

https://github.com/deveyy/bdigital-backend/pull/9/commits/a4d17c7fd6d8790b88c80552e150c774a61385dc

**Comment by ddthien-coder** [comment]
> > 
> 
> [a4d17c7](https://github.com/deveyy/bdigital-backend/commit/a4d17c7fd6d8790b88c80552e150c774a61385dc)

done!

**Review by ddthien-coder — APPROVED** [review]
approve https://github.com/deveyy/bdigital-backend/pull/9/commits/a4d17c7fd6d8790b88c80552e150c774a61385dc

**Pull request merged**
